# Generated by Django 2.1.7 on 2019-04-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190412_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='tutorial_summary',
        ),
    ]
