# Generated by Django 2.1.7 on 2019-04-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_tutorialcategory_tutorial_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_website',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
